# Исключение по паттерну из issue list
run:
  modules-download-mode: vendor
issues:
  exclude:
    - w.Write

# Исключение из errcheck по функции или пакет+функция
#linters-settings:
#  errcheck:
#    ignore: fmt:.*,Write.*