db:
  max_conn_num: 10
logger:
  file: "logfile.log"
redis:
  addr: "redis://user:@localhost:6379/0"
csrf:
  duration: 3600
fileserver:
  root: "resources"
  addr: "http://localhost:8082/"
  avatar:
    dir: "/avatar"
    default: "http://localhost:8082/avatar/default.jpg"
    types:
      "image/jpeg": "jpg"
      "image/png":  "png"
      "image/gif":  "gif"
api:
  prefix: "/api/v1/"
cors:
  allowed_origins: ["http://89.208.199.170:3000",
                    "http://195.19.37.246:10982",
                    "http://89.208.199.170:3001",
                    "http://localhost:3000",
                    "http://virusmusic.fun",
                    "https://virusmusic.fun",
                    "https://lsd.virusmusic.fun"]
  allowed_cred: true
  allowed_methods: ["GET", "POST", "PUT", "DELETE"]
  allowed_headers: ["Content-Type", "X-Content-Type-Options", "Csrf-Token"]
  debug: false
cookie:
  expire: 30
grpc:
  session: "127.0.0.1:8083"
  fileserver: "127.0.0.1:8084"
main:
  addr: ":8081"
ssl:
  key: "privkey.pem"
  fullchain: "fullchain.pem"
playlist:
  avatar:
    dir: "/playlist"