FROM golang:1.14 AS no_homo_fileserver_1
ENV GO111MODULE=on
WORKDIR /go/src/no_homo_fileserver_1
COPY fileserver /go/src/no_homo_fileserver_1
COPY resources /go/src/no_homo_fileserver_1/resources
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .

FROM alpine
WORKDIR /app
COPY --from=no_homo_fileserver_1  /go/src/no_homo_fileserver_1 /app
RUN chmod +x .
EXPOSE 8082/tcp
ENTRYPOINT [ "/app/no_homo_fileserver" ]
