// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package track is a generated GoMock package.
package track

import (
	models "github.com/2020_1_no_homomorphism/no_homo_main/internal/pkg/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetTrackById mocks base method
func (m *MockUseCase) GetTrackById(id string) (models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackById", id)
	ret0, _ := ret[0].(models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackById indicates an expected call of GetTrackById
func (mr *MockUseCaseMockRecorder) GetTrackById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackById", reflect.TypeOf((*MockUseCase)(nil).GetTrackById), id)
}

// GetBoundedTracksByArtistId mocks base method
func (m *MockUseCase) GetBoundedTracksByArtistId(id string, start, end uint64) ([]models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundedTracksByArtistId", id, start, end)
	ret0, _ := ret[0].([]models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundedTracksByArtistId indicates an expected call of GetBoundedTracksByArtistId
func (mr *MockUseCaseMockRecorder) GetBoundedTracksByArtistId(id, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundedTracksByArtistId", reflect.TypeOf((*MockUseCase)(nil).GetBoundedTracksByArtistId), id, start, end)
}

// GetBoundedTracksByAlbumId mocks base method
func (m *MockUseCase) GetBoundedTracksByAlbumId(aId string, start, end uint64) ([]models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundedTracksByAlbumId", aId, start, end)
	ret0, _ := ret[0].([]models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundedTracksByAlbumId indicates an expected call of GetBoundedTracksByAlbumId
func (mr *MockUseCaseMockRecorder) GetBoundedTracksByAlbumId(aId, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundedTracksByAlbumId", reflect.TypeOf((*MockUseCase)(nil).GetBoundedTracksByAlbumId), aId, start, end)
}

// GetBoundedTracksByPlaylistId mocks base method
func (m *MockUseCase) GetBoundedTracksByPlaylistId(plId string, start, end uint64) ([]models.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundedTracksByPlaylistId", plId, start, end)
	ret0, _ := ret[0].([]models.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundedTracksByPlaylistId indicates an expected call of GetBoundedTracksByPlaylistId
func (mr *MockUseCaseMockRecorder) GetBoundedTracksByPlaylistId(plId, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundedTracksByPlaylistId", reflect.TypeOf((*MockUseCase)(nil).GetBoundedTracksByPlaylistId), plId, start, end)
}

// Search mocks base method
func (m *MockUseCase) Search(text string, count uint) ([]models.TrackSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", text, count)
	ret0, _ := ret[0].([]models.TrackSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockUseCaseMockRecorder) Search(text, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockUseCase)(nil).Search), text, count)
}
