// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package playlist is a generated GoMock package.
package playlist

import (
	gomock "github.com/golang/mock/gomock"
	models "no_homomorphism/internal/pkg/models"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetUserPlaylists mocks base method
func (m *MockUseCase) GetUserPlaylists(id string) ([]models.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPlaylists", id)
	ret0, _ := ret[0].([]models.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPlaylists indicates an expected call of GetUserPlaylists
func (mr *MockUseCaseMockRecorder) GetUserPlaylists(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPlaylists", reflect.TypeOf((*MockUseCase)(nil).GetUserPlaylists), id)
}

// GetPlaylistById mocks base method
func (m *MockUseCase) GetPlaylistById(id string) (models.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylistById", id)
	ret0, _ := ret[0].(models.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylistById indicates an expected call of GetPlaylistById
func (mr *MockUseCaseMockRecorder) GetPlaylistById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylistById", reflect.TypeOf((*MockUseCase)(nil).GetPlaylistById), id)
}

// CheckAccessToPlaylist mocks base method
func (m *MockUseCase) CheckAccessToPlaylist(userId, playlistId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccessToPlaylist", userId, playlistId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccessToPlaylist indicates an expected call of CheckAccessToPlaylist
func (mr *MockUseCaseMockRecorder) CheckAccessToPlaylist(userId, playlistId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccessToPlaylist", reflect.TypeOf((*MockUseCase)(nil).CheckAccessToPlaylist), userId, playlistId)
}
